pipeline:
  ping:
    image: postgres
    commands:
      - bin/wait-for-postgres.sh
      - psql -U postgres -d test -h database -p 5432 -c "CREATE TABLE person( NAME TEXT );"
      - psql -U postgres -d test -h database -p 5432 -c "INSERT INTO person VALUES('john smith');"
      - psql -U postgres -d test -h database -p 5432 -c "INSERT INTO person VALUES('jane doe');"
      - psql -U postgres -d test -h database -p 5432 -c "SELECT * FROM person;"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
